# Generated by Django 3.2.15 on 2022-09-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_itemsinorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
