# Generated by Django 3.2.15 on 2022-09-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Не обработан'), ('IP', 'Собирается рестораном'), ('ID', 'В доставке'), ('OP', 'Обработан')], default='NP', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
