# Generated by Django 3.2.15 on 2022-09-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_called_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_status',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('CARD', 'Интернет-эквайринг')], default='CASH', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
