# Generated by Django 3.2.15 on 2022-09-16 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_rename_item_quantity_itemsinorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
