# Generated by Django 3.2.15 on 2022-10-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20220916_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_orders', to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
