# Generated by Django 3.2.15 on 2022-10-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_itemsinorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
